{{- $releaseName := .Release.Name -}}
{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  name: {{ $releaseName }}
spec:
  rules:
{{- range .Values.ingressSS.hosts }}
  - host: {{ . }}
    http:
      paths:
        - backend:
            serviceName: {{ $releaseName }}
            servicePort: 8081
{{- end -}}
{{- end -}}
