apiVersion: v1
kind: Service
metadata:
  labels:
    app: tiny
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 8089
    targetPort: http
    name: http
  selector:
    app: {{ .Release.Name }}
