replicas: 1
image:
  repository: ciapatti79/tiny-container
  tag: 0.21
  pullPolicy: Always

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
  path: /
  host: tiny-container.20.67.66.98.nip.io

